#!/usr/bin/env node
/**
 * GENERATED BY constraints-generate-tests — DO NOT EDIT THIS FILE.
 *
 * Runs the constraints test suite with Node's built-in test runner.
 *
 *   node constraints-tests/run.mjs
 *
 * This wrapper exists because how you point `node --test` at a directory is not
 * portable across Node versions: Node 18/20 treat positional arguments as file
 * paths, while Node 22+ treat them as glob patterns (so a bare directory name
 * fails with MODULE_NOT_FOUND). Running with no positional arguments and the
 * working directory set to this folder performs a recursive search on every
 * supported version.
 */
import { spawn } from "node:child_process";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

const child = spawn(process.execPath, ["--test", ...process.argv.slice(2)], {
  cwd: here,
  stdio: "inherit",
});

child.on("exit", (code, signal) => {
  process.exit(signal ? 1 : (code ?? 1));
});

child.on("error", (error) => {
  console.error("failed to start the test runner:", error.message);
  process.exit(1);
});
